# Generated by Django 5.0.1 on 2024-01-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0004_rename_telfone_pet_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
